### ISSUE TITLE
TODO Reproducibility

### ISSUE THREAD

**Issue by LucasKook** [LucasKook/dtm-usz-stroke#1]
- [ ] Upload intermediate results
- [ ] Comment/format code according to guidelines
- [ ] Check reproducibility on server
- [ ] Describe folder structure
- [ ] Add session info to README
- [ ] Write Makefile
- [ ] Check reproducibility with `make`
